### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by awreh** [squi2rel/node-mindustry#2]
Hi, I don't know where else to write for help, it's not really about your code, I'm doing about the same thing as you but from scratch, I have a problem that I can't solve for 2 weeks now, if I send details can you help me?

**Comment by squi2rel** [comment]
You're here. I can provide help as much as possible.

**Comment by awreh** [comment]
I have the code
```
 function rs(buffer, off){
	let str = buffer.readUInt8(off); off += 1;
	if(str){
		let len = buffer.readUInt16BE(off); off += 2;
		let data = buffer.slice(off, off + len)
		return [data, off]
	} else {
		return ['', off]
	}
}

function ro(buffer, offset){
	let obj = {}
	let size = buffer.readInt16BE(offset);
	for(let i = 0; i < size; i++){
		let key, value;
		[key, offset] = rs(buffer, offset)
		[value, offset] = rs(buffer, offset)
		obj[key] = value
	}
	return [obj, offset]
}

function hs(buf){
	let ubuf = zlib.inflateSync(buf);
	let offset = 0;
    let rules = '';
    let obj = {}
    [rules, offset] = rs(ubuf, offset);
    [obj, offset] = ro(ubuf, offset);
    let wave = ubuf.readUInt32BE(offset); offset += 4;
    console.log("wave: ” + wave);
}
```
 which reads worldstream but after running it writes ‘wave: 2031616’ or any other big number, I don't understand what is wrong in this code

**Comment by squi2rel** [comment]
So rs function should read a String right? This is referred to DataInputStream#readUTF(), and it is a DataInputStream
https://github.com/squi2rel/node-mindustry/blob/c3e7275be149931aa490f9d8f222dd855117094c/lib/DataStream.js#L150-L152
not a Reads
https://github.com/squi2rel/node-mindustry/blob/c3e7275be149931aa490f9d8f222dd855117094c/lib/TypeIO.js#L13-L20

You should just read a short as a length. There isn't have a bit as null mark

**Comment by awreh** [comment]
Okay, now I've changed the rs to
```
function rs(buffer, off){
	let len = buffer.readUInt16BE(off); off += 2;
	let data = buffer.slice(off, off + len)
	return [data, off + len]
}
```
 but now I get an error The value of “offset” is out of range.

**Comment by squi2rel** [comment]
In your ro function, after reading short, the offset didn't change.

**Comment by awreh** [comment]
sorry for taking up your time, thanks for pointing out the error! I fixed it and now the code looks like this:
```
function rs(buffer, off){
	let len = buffer.readUInt16BE(off); off += 2;
	let data = buffer.slice(off, off + len)
	return [data, off + len]
}

function ro(buffer, offset){
	let obj = {}
	let size = buffer.readInt16BE(offset); offset += 2;
	for(let i = 0; i < size; i++){
		let key, value;
		[key, offset] = rs(buffer, offset)
		[value, offset] = rs(buffer, offset)
		obj[key] = value
	}
	return [obj, offset]
}

function hs(buf){
	let ubuf = zlib.inflateSync(buf);
	let offset = 0;
    let rules = '';
    let obj = {};
    [rules, offset] = rs(ubuf, offset);
    [obj, offset] = ro(ubuf, offset);
    let wave = ubuf.readUInt32BE(offset); offset += 4;
    console.log("wave: " + wave);
}
```
but the code still says wave: 290421 again.

**Comment by squi2rel** [comment]
There is nothing wrong about the code. The problem is about your **Semicolons**.
# Semicolon
Look at your ro function. 
```
		[key, offset] = rs(buffer, offset)
		[value, offset] = rs(buffer, offset)
```
In the javascript interpreter, this looks like
`		[key, offset] = rs(buffer, offset)[value, offset] = rs(buffer, offset)`
So offset just increased once instead of twice.

To fix this problem, simply add a **Semicolon** after every statement.

Thanks for inventing JavaScript

**Comment by awreh** [comment]
Thank you so much. I don't know how I missed that.
