### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by awreh** [squi2rel/node-mindustry#3]
what is the value you're getting here:
https://github.com/squi2rel/node-mindustry/blob/c3e7275be149931aa490f9d8f222dd855117094c/lib/NetClient.js#L132

**Comment by squi2rel** [comment]
It is about the Player entity. Mindustry use component to build entity. I don't have enough time to implement it.

**Comment by awreh** [comment]
What does this particular field What does this particular field do? I only know what the next field after this one does.

**Comment by squi2rel** [comment]
Because all entity's read/write is auto generated, you need to compile Mindustry and then the Player entity can be found under mindustry.gen package.
Here is the Player component: https://github.com/Anuken/Mindustry/blob/v146/core/src/mindustry/entities/comp/PlayerComp.java

**Comment by squi2rel** [comment]
> What does this particular field What does this particular field do? I only know what the next field after this one does.

This is the player id

**Comment by awreh** [comment]
@squi2rel Can I contact you in any other way besides github issues or twitter? like discord or something?

**Comment by awreh** [comment]
@squi2rel ??

**Comment by squi2rel** [comment]
Anyway, my most active platform is still github. I have discord and twitter but I hardly check them. Maybe you need my email. I check it every day.
`501410836@qq.com`

**Comment by awreh** [comment]
@squi2rel Check your e-mail, please.

**Comment by awreh** [comment]
@squi2rel please help me again, open the e-mail.

**Comment by awreh** [comment]
@squi2rel please help me again, open the e-mail.
